#!/usr/bin/env python3

"""a quick script to generate solutions to Kepler problem and associated GW strain
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

### define constants

#-------------------------------------------------


